version: "3"
services:
  worker:
    hostname: worker
    container_name: worker
    image: enigmampc/external_worker_hw:testnet
    restart: unless-stopped
    environment:
      - ENIGMA_ENV=TESTNET
      - SGX_MODE=HW
      - ETH_NODE_ADDRESS=http://parity.enigma.co:8545
      - KEY_MANAGEMENT_ADDRESS=http://km-testnet.enigma.co:3040
      - MIN_CONFIRMATIONS=3
    ports:
      - "3346:3346"   # Json RPC
      - "10300:10300" # LibP2P
    volumes:
      - ./config/.enigma:/root/.enigma
    devices:
      - "/dev/isgx:/dev/isgx"
